<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sohel-PC" failures="1" tests="3" name="automation_test.mortgage_calculator.CalculateApr" time="82.105" errors="0" timestamp="2021-04-03T17:06:37 EDT" skipped="2">
  <testcase classname="automation_test.mortgage_calculator.CalculateApr" name="calculateRealApr" time="29.844">
    <skipped/>
  </testcase> <!-- calculateRealApr -->
  <system-out/>
  <testcase classname="automation_test.mortgage_calculator.CalculateApr" name="calculateRealApr" time="21.706">
    <failure message="expected [3.4%] but found [3.132%]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [3.4%] but found [3.132%]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at page_objects.RealApr.validateAPR(RealApr.java:76)
at automation_test.mortgage_calculator.CalculateApr.calculateRealApr(CalculateApr.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- calculateRealApr -->
  <system-out/>
  <testcase classname="automation_test.mortgage_calculator.CalculateApr" name="calculateRealApr" time="30.555">
    <skipped/>
  </testcase> <!-- calculateRealApr -->
  <system-out/>
</testsuite> <!-- automation_test.mortgage_calculator.CalculateApr -->
